# 模型配置
model:
  # 指定要使用的模型类，这里是 diffbir.model.swinir 模块中的 SwinIR 类
  swinir:
    target: diffbir.model.swinir.SwinIR
    # 模型的参数设置
    params:
      # 输入图像的大小，表示图像的高度和宽度
      img_size: 64
      # 图像分块的大小，表示每个块的高度和宽度
      patch_size: 1
      # 输入通道数，表示输入图像的颜色通道数（例如，RGB 图像为 3）
      in_chans: 3
      # 嵌入维度，表示特征图的通道数
      embed_dim: 180
      # 每个阶段的深度，表示每个阶段的层数
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      # 每个阶段的注意力头数，表示每个阶段的注意力机制的头数
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      # 窗口大小，表示注意力机制中窗口的大小
      window_size: 8
      # MLP 比率，表示 MLP 层的扩展比例
      mlp_ratio: 2
      # 缩放因子，表示输出图像的缩放比例
      sf: 8
      # 图像范围，表示输入图像的像素值范围
      img_range: 1.0
      # 上采样方法，表示使用的上采样技术
      upsampler: "nearest+conv"
      # 残差连接方式，表示残差连接的类型
      resi_connection: "1conv"
      # 是否进行反打乱操作
      unshuffle: True
      # 反打乱的缩放比例
      unshuffle_scale: 8

# 数据集配置
dataset:
  # 训练数据集配置
  train:
    # 指定要使用的数据集类，这里是 diffbir.dataset.codeformer 模块中的 CodeformerDataset 类
    target: diffbir.dataset.codeformer.CodeformerDataset
    # 数据集的参数设置
    params:
      # 训练文件列表路径
      file_list: 
      # 文件后端配置
      file_backend_cfg:
        target: diffbir.dataset.file_backend.HardDiskBackend
      # 输出图像的大小
      out_size: 512
      # 裁剪类型
      crop_type: center
      # 模糊核大小
      blur_kernel_size: 41
      # 模糊核类型列表
      kernel_list: ['iso', 'aniso']
      # 模糊核概率
      kernel_prob: [0.5, 0.5]
      # 模糊 sigma 范围
      blur_sigma: [0.1, 12]
      # 下采样范围
      downsample_range: [1, 12]
      # 噪声范围
      noise_range: [0, 15]
      # JPEG 压缩范围
      jpeg_range: [30, 100]
  # 验证数据集配置
  val:
    # 指定要使用的数据集类，这里是 diffbir.dataset.codeformer 模块中的 CodeformerDataset 类
    target: diffbir.dataset.codeformer.CodeformerDataset
    # 数据集的参数设置
    params:
      # 验证文件列表路径
      file_list: 
      # 文件后端配置
      file_backend_cfg:
        target: diffbir.dataset.file_backend.HardDiskBackend
      # 输出图像的大小
      out_size: 512
      # 裁剪类型
      crop_type: center
      # 模糊核大小
      blur_kernel_size: 41
      # 模糊核类型列表
      kernel_list: ['iso', 'aniso']
      # 模糊核概率
      kernel_prob: [0.5, 0.5]
      # 模糊 sigma 范围
      blur_sigma: [0.1, 12]
      # 下采样范围
      downsample_range: [1, 12]
      # 噪声范围
      noise_range: [0, 15]
      # JPEG 压缩范围
      jpeg_range: [30, 100]

# 批处理转换配置
batch_transform:
  # 指定要使用的批处理转换类，这里是 diffbir.dataset.batch_transform 模块中的 IdentityBatchTransform 类
  target: diffbir.dataset.batch_transform.IdentityBatchTransform

# 训练配置
train:
  # 实验目录路径
  exp_dir: 
  # 学习率
  learning_rate: 1e-4
  # 总批处理大小
  batch_size: 96
  # 工作线程数
  num_workers: 
  # 训练步数
  train_steps: 150000
  # 日志记录频率
  log_every: 50
  # 检查点保存频率
  ckpt_every: 10000
  # 图像保存频率
  image_every: 1000
  # 验证频率
  val_every: 1000
  # 是否恢复训练
  resume: ~
