# 模型配置
model:
  # 指定要使用的模型类，这里是 diffbir.model.cldm 模块中的 ControlLDM 类
  cldm:
    target: diffbir.model.cldm.ControlLDM
    # 模型的参数设置
    params:
      # 潜在空间的缩放因子
      latent_scale_factor: 0.18215
      # UNet 配置
      unet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      # VAE 配置
      vae_cfg:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      # CLIP 配置
      clip_cfg:
        embed_dim: 1024
        vision_cfg:
          image_size: 224
          layers: 32
          width: 1280
          head_width: 80
          patch_size: 14
        text_cfg:
          context_length: 77
          vocab_size: 49408
          width: 1024
          heads: 16
          layers: 24
        layer: "penultimate"
      # ControlNet 配置
      controlnet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

  # 指定要使用的模型类，这里是 diffbir.model.swinir 模块中的 SwinIR 类
  swinir:
    target: diffbir.model.swinir.SwinIR
    # 模型的参数设置
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

  # 指定要使用的模型类，这里是 diffbir.model.gaussian_diffusion 模块中的 Diffusion 类
  diffusion:
    target: diffbir.model.gaussian_diffusion.Diffusion
    # 模型的参数设置
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000
      zero_snr: True
      parameterization: v

# 数据集配置
dataset:
  # 训练数据集配置
  train:
    # 指定要使用的数据集类，这里是 diffbir.dataset.realesrgan 模块中的 RealESRGANDataset 类
    target: diffbir.dataset.realesrgan.RealESRGANDataset
    # 数据集的参数设置
    params:
      # 文件元数据路径
      file_metas:
        # 训练集格式为 parquet 文件，每行包含高质量图像的文件路径、长描述和短描述
        - file_list: 
          image_path_key: image_path
          short_prompt_key: llava_short
          long_prompt_key: llava_long

      p_long_prompt: 0.2

      file_backend_cfg:
        target: diffbir.dataset.file_backend.HardDiskBackend

      out_size: 512
      crop_type: none

      use_hflip: false
      use_rot: false

      blur_kernel_size: 21
      kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob: 0.1
      blur_sigma: [0.2, 3]
      betag_range: [0.5, 4]
      betap_range: [1, 2]

      blur_kernel_size2: 21
      kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob2: 0.1
      blur_sigma2: [0.2, 1.5]
      betag_range2: [0.5, 4]
      betap_range2: [1, 2]

      final_sinc_prob: 0.8

      p_empty_prompt: 0.2

# 批处理转换配置
batch_transform:
  # 指定要使用的批处理转换类，这里是 diffbir.dataset.batch_transform 模块中的 RealESRGANBatchTransform 类
  target: diffbir.dataset.batch_transform.RealESRGANBatchTransform
  # 批处理转换的参数设置
  params:
    use_sharpener: true
    # 训练池的队列大小，这应该是 batch_size 的倍数（每个 GPU）
    queue_size: 256
    # 第一个降质过程
    resize_prob: [0.2, 0.7, 0.1] # up, down, keep
    resize_range: [0.15, 1.5]
    gaussian_noise_prob: 0.5
    noise_range: [1, 30]
    poisson_scale_range: [0.05, 3]
    gray_noise_prob: 0.4
    jpeg_range: [30, 95]

    # 第二个降质过程
    stage2_scale: 4
    second_blur_prob: 0.8
    resize_prob2: [0.3, 0.4, 0.3] # up, down, keep
    resize_range2: [0.3, 1.2]
    gaussian_noise_prob2: 0.5
    noise_range2: [1, 25]
    poisson_scale_range2: [0.05, 2.5]
    gray_noise_prob2: 0.4
    jpeg_range2: [30, 95]

# 训练配置
train:
  # 预训练的 SD v2.1-zsnr 路径
  sd_path: 
  # 实验目录路径
  exp_dir: 
  # 阶段 1 的 SwinIR 路径
  # 对于 DiffBIR v2.1，我们使用在 ImageNet-1k 上训练的 SwinIR，使用 RealESRGAN 降质
  swinir_path: 
  learning_rate: 1e-5
  batch_size: 512
  num_workers: 16
  train_steps: 1000000
  log_every: 100
  ckpt_every: 10000
  image_every: 1000
  resume: 
  noise_aug_timestep: 200
